config_version : 0

name: pythonDummy

version: 0.1.36

uuid: 3eb1be1c-e981-475f-8c3f-e4700c409cd1

authors:
- olli

description: >
 Simple test package for testing rez/git interoperation

variants:
- [ Linux ]

requires:
- python-2.6+<3

commands:
- export PATH=$PATH:!ROOT!/bin
- export PYTHONPATH=$PYTHONPATH:!ROOT!/python
